version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/skilldraft
    depends_on:
      - mysql
    command: npm run dev --prefix ./Backend
    networks:
      - skilldraft_network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skilldraft
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - skilldraft_network

volumes:
  mysql_data:

networks:
  skilldraft_network:
