version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    environment:
      - DATABASE_URL=postgresql://XactXray5:b538b73a-e575-4e7e-bd46-7875cb8a127c-9z383@db.ezhost-edu.dev:30096/skilldraft-u0lv2b

    depends_on:
      - postgres
    command: npm run dev --prefix ./Backend
    networks:
      - skilldraft_network

  postgres:
    image: postgres:15
    ports:
      - '30096:5432'
    environment:
      POSTGRES_USER: XactXray5
      POSTGRES_PASSWORD: b538b73a-e575-4e7e-bd46-7875cb8a127c-9z383
      POSTGRES_DB: skilldraft-u0lv2b
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - skilldraft_network

volumes:
  postgres_data:

networks:
  skilldraft_network:
