services:
  # Service MySQL
  mysql:
    image: mysql:8.0
    container_name: skilldraft_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skilldraft
      MYSQL_USER: skilldraft_user
      MYSQL_PASSWORD: skilldraft_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - skilldraft_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Service Backend Node.js
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skilldraft_backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: "mysql://root:root@mysql:3306/skilldraft"
      JWT_SECRET: a782055681b56b2141a6831dd35e58e6509ae60ffb33801ff7566cbe553020c7e226a58605b5abb486f5347474cd1cdfa2a9566b27471f82568d3d8ca3032da0a5264bd4598338bea1466f80c3b322c7968432029f3a4caf308de72bbb278afe18914860fe845ab1bed2df5046f6029395c49ccf0a5a1014cc02a8efe7db9a6a1be64987ed7cd4f3453c31dd40012a2fcbec916c9c9013545087eb6f2d880ac79e8b997e2bb06fb64f41e8b57c719d0b1f3dc91f39199bbe9c5e0441069f04463b5dadd433a9075bf33f0053dbd055e523a53847ec47147090ac3b76abb174650d9d4ab7c0a6cebdccb5626d7028147d79960f782a264b09882f49a4383c75b6
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - skilldraft_network
    command: sh -c "sleep 10 && npm run dev"

volumes:
  mysql_data:

networks:
  skilldraft_network:
    driver: bridge